feat: add user route
OmarZubaidi/Wanderlust pull request #5
Opened 2022-05-07 20:43 UTC by stefanfeldner

2022-05-07 20:49 UTC, daniele24134 requested changes
change the name of the file from user.ts to types.ts if you have to put them all in a single file. That I approve btw

2022-05-07 21:05 UTC, daniele24134 approved these changes

2022-05-08 10:58 UTC, CosmicZanna approved these changes

2022-05-08 12:16 UTC, OmarZubaidi approved these changes

2022-05-08 12:16 UTC, merged